branch-defaults:
  main:
    environment: Jiffy-Explorer
  master:
    environment: Jiffy-Explorer
    group_suffix: null
environment-defaults:
  Highfi-chat-client:
    branch: null
    repository: null
global:
  application_name: Jiffy
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
