sources:
  - name: userOpIndexer
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/lazycoder1/{context.indexerName:georli-jiffy-scan}
  # - name: mumbaiIndex
  #   handler:
  #     graphql:
  #       endpoint: https://api.thegraph.com/subgraphs/name/lazycoder1/mumbai-aa-indexer

additionalTypeDefs: |
  extend type UserOp {
    indexerName: String
  }
  extend type Query {
    crossUserOps(
      orderBy: UserOp_orderBy,
      orderDirection: OrderDirection,
      where: UserOp_filter, 
      skip: Int = 0,
      first: Int = 100,
      indexerNames: [String!]!
    ): [UserOp!]!
  }

additionalResolvers:
  - ./utils/resolver

documents:
  - ./queries/blockNumberQuery.graphql
  - ./queries/userOpQuery.graphql
  - ./queries/addressActivityQuery.graphql
  - ./queries/paymasterActivityQuery.graphql
  - ./queries/latestTransactions.graphql
  - ./queries/beneficiaryActivityQuery.graphql
  - ./queries/targetQuery.graphql
  - ./queries/getFactoryAccounts.graphql
  - ./queries/getLatestAccounts.graphql

  

codegen:
  contextType: 'MeshContext & { indexerName: string }'